language: node_js
node_js:
    - '12' # EOL: April 2022
    - '10' # EOL: April 2021

jobs:
    include:
        - stage: deploy
          node_js: "lts/*"
          script: skip
          before_deploy: if [ "$TRAVIS_BRANCH" = master ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm version prerelease --no-git-tag-version --preid "$TRAVIS_BUILD_NUMBER"; fi
          deploy:
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: Q3vAuqEpLQdl4idbWEiISX4DJo0WVhMaKpfSthuz2hhiOfgHM/Rmik0MgUnG8LAzli3/rI+xQ2nPT9dyA2Fg8+hKbGCKJIqoZAW0rchGghhK8zDnSPa9RxjksMyoDoUvslnflySla/76AW9EJolPT2JiwTl1yfzjVrUmhWrhhKKfchLxRcZh2THCKxHpdhTZESSJO+tV6W0/8HztZ15W2BRRE7vOf7fcNIXeulVhIYYjcUZKiZccguL7jSX+OTlV1VMmIwRhQDQwfbvQRG0uPKMNm+0p7MZghvAXaeyo++AVbvTWXFzMrKI4q2uViUhY3dKyifLvDDqWLwFJyO9IuL1QhFru5ne6VuFpjgqIoEWlOzCSsvScPxzbRsTSHroM8UUH15TI6b26EjX857OFEeIlvxWIf+LkG1zlyZFeTV36H/V49NVkYMLWbWNQhu4zDgs+GznvvAwHas5cVS2InUfB3vjQrlMF4fSNhj4vpLXHpekS53+yi1f8dN3RzZygsvDNTloX/n0hcDJ/9b1d4FoEZu+N1/xLez0TmWIY8S4aarEaOhonqhUHoBFtcTSYUV+Z9WMWG2eCJG1CFgYDm/Ps1FTSbDtRk2flD6CHpQXPnx6kh8+6aLFFTdC6EEl0+ajjgasplbTAE37pAandWlXqeoO9neQUsc3zpHDQksE=
                tag: next
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: Q3vAuqEpLQdl4idbWEiISX4DJo0WVhMaKpfSthuz2hhiOfgHM/Rmik0MgUnG8LAzli3/rI+xQ2nPT9dyA2Fg8+hKbGCKJIqoZAW0rchGghhK8zDnSPa9RxjksMyoDoUvslnflySla/76AW9EJolPT2JiwTl1yfzjVrUmhWrhhKKfchLxRcZh2THCKxHpdhTZESSJO+tV6W0/8HztZ15W2BRRE7vOf7fcNIXeulVhIYYjcUZKiZccguL7jSX+OTlV1VMmIwRhQDQwfbvQRG0uPKMNm+0p7MZghvAXaeyo++AVbvTWXFzMrKI4q2uViUhY3dKyifLvDDqWLwFJyO9IuL1QhFru5ne6VuFpjgqIoEWlOzCSsvScPxzbRsTSHroM8UUH15TI6b26EjX857OFEeIlvxWIf+LkG1zlyZFeTV36H/V49NVkYMLWbWNQhu4zDgs+GznvvAwHas5cVS2InUfB3vjQrlMF4fSNhj4vpLXHpekS53+yi1f8dN3RzZygsvDNTloX/n0hcDJ/9b1d4FoEZu+N1/xLez0TmWIY8S4aarEaOhonqhUHoBFtcTSYUV+Z9WMWG2eCJG1CFgYDm/Ps1FTSbDtRk2flD6CHpQXPnx6kh8+6aLFFTdC6EEl0+ajjgasplbTAE37pAandWlXqeoO9neQUsc3zpHDQksE=
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
                    tags: true
