language: node_js
node_js:
    - '12' # EOL: April 2022
    - '10' # EOL: April 2021

jobs:
    include:
        - stage: deploy
          node_js: "lts/*"
          script: skip
          before_deploy: if [ "$TRAVIS_BRANCH" = master ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm version prerelease --no-git-tag-version --preid "$TRAVIS_BUILD_NUMBER"; fi
          deploy:
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: clSA+l0+pxr3QQ5LflbIh8smZprMeBJMcH6x4Im7Lb1o2nXIf/XvWw8//10ruuXZp0hpCFs/tpLMGdkDJ/8lT5EiXO5OUGETdbd5ocktmTGfAT00dneZB2rbwPlGPR7/d4QlZDH84qSJWL96GOy+GBoE1fCwRhxbJxZMm6EMEJ5gnXsSGu6JYwdTkSZ8D8ebXJwwFOk+CPQZBR2gjujW8ztaDAs073zE8RBMZH4xJ8RL3QxbUCw155BSldzGR5W27NcvjJAXVDxVQVr13dgGy/AMW0icfHD/S24nIgJ3nZa3BVkz5HaSE+0V0om+Iwmn33HYa+7oTzdYMQK99aSQFi5Jbe8SJUKYf0sYIgvcptHb7J4+29gncegDLaBBTxyld1rFN4P5R/nCiM7Leks6Qr2Gjl17oXf4jX+v6REgp+slX0pakcwEs9iBmIKAHXx7xJWfqYxrveTprPAhofLn3Tx6FgVjPdMM72bnddayqcycARblrF/7z2Y6f94ean3RJrVM6rRynwh+ZzgtLUyceoP35fUOa55qztoy1PhB/jliELz6Mv33OD3MFXuAuKEbFPv40/6tmbDpm9UWBY/IJluNCkEozXH78rzA/U476U1Ktp8iamDKbXMgHgE3X8eUQOOGzllDRms02n9WBV8FVQYWH/bf+lCjRWFh1Kg0sMQ=
                tag: next
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: clSA+l0+pxr3QQ5LflbIh8smZprMeBJMcH6x4Im7Lb1o2nXIf/XvWw8//10ruuXZp0hpCFs/tpLMGdkDJ/8lT5EiXO5OUGETdbd5ocktmTGfAT00dneZB2rbwPlGPR7/d4QlZDH84qSJWL96GOy+GBoE1fCwRhxbJxZMm6EMEJ5gnXsSGu6JYwdTkSZ8D8ebXJwwFOk+CPQZBR2gjujW8ztaDAs073zE8RBMZH4xJ8RL3QxbUCw155BSldzGR5W27NcvjJAXVDxVQVr13dgGy/AMW0icfHD/S24nIgJ3nZa3BVkz5HaSE+0V0om+Iwmn33HYa+7oTzdYMQK99aSQFi5Jbe8SJUKYf0sYIgvcptHb7J4+29gncegDLaBBTxyld1rFN4P5R/nCiM7Leks6Qr2Gjl17oXf4jX+v6REgp+slX0pakcwEs9iBmIKAHXx7xJWfqYxrveTprPAhofLn3Tx6FgVjPdMM72bnddayqcycARblrF/7z2Y6f94ean3RJrVM6rRynwh+ZzgtLUyceoP35fUOa55qztoy1PhB/jliELz6Mv33OD3MFXuAuKEbFPv40/6tmbDpm9UWBY/IJluNCkEozXH78rzA/U476U1Ktp8iamDKbXMgHgE3X8eUQOOGzllDRms02n9WBV8FVQYWH/bf+lCjRWFh1Kg0sMQ=
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
                    tags: true
