language: node_js
node_js:
    - '12' # EOL: April 2022
    - '10' # EOL: April 2021

jobs:
    include:
        - stage: deploy
          node_js: "lts/*"
          script: skip
          before_deploy: if [ "$TRAVIS_BRANCH" = master ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm version prerelease --no-git-tag-version --preid "$TRAVIS_BUILD_NUMBER"; fi
          deploy:
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: TIsf37WFuMgRWRVpQYK8tXQbpm58qIFxcTLFQqsnChPVgtSLGBCjBNqVfPepTBYlN3vAwIXldIS+7jy/tRgTYAAPAGtbj2nyrl3n02h51rsMLDs+arDZJbgdezY0xJSxNzCG7wOEtLCitu4Y49Ub903N74BWn1FK28n4CZWfz1L+KB/CfPv7IuneF/MkNFrSF8BE9dXVfyZHIZ0gjQOtDwfg4DCBVR/8/LMZwd5znRioTJmp48KURQYh9BguyD1bNi91hghHGw7Hcot62pGDkW67rZXrhnUbNA8OdXgzMe/LByQdIcmYSK1RP7bHcj9oMd/bj6g4bxsxNqIYWqm99ZzXYcd/zMuzpqlb4r9JfW3XBX5Q6aQcDRJTkpFuKq2IhbO1ZBEqFrAXN7e3Vb+1r5nqXqj9i8bZQKacce+cIgqpDRFQFHa7mNdZt3kkrbEiNpjNWYd0lkTD/P/8oYQtajy5ZVe2PvpbcaKThi0VfrsALeiK/bRtCxeM16A0Tfqlcak2W41IIJJdGxcT4AgHO6iB1Y1ImXy06jb+d3FnUgxtp6Iim0CTH0mBHMnM+aQcJrjbrJgm5aZc/ximDJnc4luL6BrT+yLRsCHynDtRoOYLPSsyQVvZizDPiLay//hhmKqvFxhtXbKmjnTvbKZ7E19N84hG8ljkmT6nuSpix68=
                tag: next
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: TIsf37WFuMgRWRVpQYK8tXQbpm58qIFxcTLFQqsnChPVgtSLGBCjBNqVfPepTBYlN3vAwIXldIS+7jy/tRgTYAAPAGtbj2nyrl3n02h51rsMLDs+arDZJbgdezY0xJSxNzCG7wOEtLCitu4Y49Ub903N74BWn1FK28n4CZWfz1L+KB/CfPv7IuneF/MkNFrSF8BE9dXVfyZHIZ0gjQOtDwfg4DCBVR/8/LMZwd5znRioTJmp48KURQYh9BguyD1bNi91hghHGw7Hcot62pGDkW67rZXrhnUbNA8OdXgzMe/LByQdIcmYSK1RP7bHcj9oMd/bj6g4bxsxNqIYWqm99ZzXYcd/zMuzpqlb4r9JfW3XBX5Q6aQcDRJTkpFuKq2IhbO1ZBEqFrAXN7e3Vb+1r5nqXqj9i8bZQKacce+cIgqpDRFQFHa7mNdZt3kkrbEiNpjNWYd0lkTD/P/8oYQtajy5ZVe2PvpbcaKThi0VfrsALeiK/bRtCxeM16A0Tfqlcak2W41IIJJdGxcT4AgHO6iB1Y1ImXy06jb+d3FnUgxtp6Iim0CTH0mBHMnM+aQcJrjbrJgm5aZc/ximDJnc4luL6BrT+yLRsCHynDtRoOYLPSsyQVvZizDPiLay//hhmKqvFxhtXbKmjnTvbKZ7E19N84hG8ljkmT6nuSpix68=
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/eslint-config
                    tags: true
